server:
  port: 8091


spring:
  application:
    name: "user-service"
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service-db
    username: *******
    password: *******
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: person
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
